"""
Pydantic models for image processing and API responses.
"""

from pydantic import BaseModel, Field


class ImageUploadResponse(BaseModel):
    """Response model for image upload."""

    success: bool = Field(..., description="Whether the upload was successful")
    message: str = Field(..., description="Response message")
    image_id: str | None = Field(None, description="Unique image identifier")
    analysis_status: str = Field(default="pending", description="Analysis status")
    description: str | None = Field(None, description="Detailed image description from OpenAI")
    threejs_code: str | None = Field(None, description="Three.js code for 3D rendering generated by OpenAI")


class ImageAnalysisRequest(BaseModel):
    """Request model for image analysis."""

    image_id: str = Field(..., description="Image identifier to analyze")
    analysis_type: str = Field(default="general", description="Type of analysis to perform")


class ImageAnalysisResponse(BaseModel):
    """Response model for image analysis."""

    success: bool = Field(..., description="Whether the analysis was successful")
    image_id: str = Field(..., description="Image identifier")
    analysis_type: str = Field(..., description="Type of analysis performed")
    results: dict = Field(..., description="Analysis results")
    metadata: dict | None = Field(None, description="Additional metadata")


class ErrorResponse(BaseModel):
    """Error response model."""

    error: str = Field(..., description="Error type")
    message: str = Field(..., description="Error message")
    details: dict | None = Field(None, description="Additional error details")
